-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 21:45:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema M-git
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema M-git
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `M-git` DEFAULT CHARACTER SET utf8 ;
USE `M-git` ;

-- -----------------------------------------------------
-- Table `M-git`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`Student` (
  `id` INT(8) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `grade` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`online_ board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`online_ board` (
  `name` VARCHAR(20) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`post` (
  `post_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(20) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `borad_name` VARCHAR(20) NOT NULL,
  `Student_id` INT(8) NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_post_online board_idx` (`borad_name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `borad_name_UNIQUE` (`borad_name` ASC) VISIBLE,
  INDEX `fk_post_Student1_idx` (`Student_id` ASC) VISIBLE,
  UNIQUE INDEX `Student_id_UNIQUE` (`Student_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_online board`
    FOREIGN KEY (`borad_name`)
    REFERENCES `M-git`.`online_ board` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `M-git`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`schedule` (
  `Student_id` INT(8) NOT NULL,
  `schedule_name` VARCHAR(20) NOT NULL,
  `schedule_location` VARCHAR(45) NOT NULL,
  `schedule_weekday` TINYINT(1) NOT NULL,
  `professor` VARCHAR(45) NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `manual` VARCHAR(60) NOT NULL,
  INDEX `fk_schedule_item_Student1_idx` (`Student_id` ASC) VISIBLE,
  PRIMARY KEY (`Student_id`),
  CONSTRAINT `fk_schedule_item_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `M-git`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`comment` (
  `comment_id` INT NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  `author` VARCHAR(20) NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `post_id` INT NOT NULL,
  `Student_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`comment_id` ASC) VISIBLE,
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC) VISIBLE,
  INDEX `fk_comment_Student1_idx` (`Student_id` ASC) VISIBLE,
  UNIQUE INDEX `Student_id_UNIQUE` (`Student_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `M-git`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `M-git`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`UserData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`UserData` (
  `Student_id` INT(8) NOT NULL,
  INDEX `fk_UserData_Student1_idx` (`Student_id` ASC) VISIBLE,
  PRIMARY KEY (`Student_id`),
  CONSTRAINT `fk_UserData_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `M-git`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`Gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`Gallery` (
  `gallery_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gallery_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`jobs` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`IT newsLetter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`IT newsLetter` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`information` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`schedule` (
  `Student_id` INT(8) NOT NULL,
  `schedule_name` VARCHAR(20) NOT NULL,
  `schedule_location` VARCHAR(45) NOT NULL,
  `schedule_weekday` TINYINT(1) NOT NULL,
  `professor` VARCHAR(45) NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `manual` VARCHAR(60) NOT NULL,
  INDEX `fk_schedule_item_Student1_idx` (`Student_id` ASC) VISIBLE,
  PRIMARY KEY (`Student_id`),
  CONSTRAINT `fk_schedule_item_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `M-git`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `M-git`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `M-git`.`menu` (
  `weekday` TINYINT NOT NULL,
  `timeStamp` TIMESTAMP NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`weekday`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
